version: '3.8'

services:
  verification_node:
    build: .
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/video0
      - /dev/vchiq
    environment:
      - LIBCAMERA_LOG_LEVELS=3
    volumes:
      - /dev/shm:/dev/shm
