version: '3.8'

services:
  verification_node:
    build: .
    container_name: picamera
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/video0
      - /dev/vchiq
    environment:
      - LIBCAMERA_LOG_LEVELS=3
    volumes:
      - /dev/shm:/dev/shm
      - /lib:/lib:ro
      - /usr/lib:/usr/lib:ro
      - /usr/share:/usr/share:ro