version: '3.8'

services:
  verification_node:
    build: .
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/vchiq
      - /dev/video0
    volumes:
      - /dev/shm:/dev/shm
